<a href="https://colab.research.google.com/github/Jacobluke-/FYPI/blob/main/Pytorch_Tutorial/Some%20minor%20exercise%20on%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.manual_seed(1)

In [2]:
x_1 = torch.randn(2,5)
y_1 = torch.randn(3,5)
z_1 = torch.cat([x_1,y_1])
print(x_1,"\n",y_1,"\n",z_1)
# This concatenates along the first axis(row)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]]) 
 tensor([[-0.8923, -0.0583, -0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770,  0.3255]]) 
 tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [-0.8923, -0.0583, -0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770,  0.3255]])


In [3]:
x_2 = torch.randn(2,3)
y_2 = torch.randn(2,5)
# The second argument specifies which axis to concatenate along
z_2 = torch.cat([x_2,y_2],1)
print(x_2,"\n",y_2,"\n",z_2)

tensor([[-0.4791,  1.3790,  2.5286],
        [ 0.4107, -0.9880, -0.9081]]) 
 tensor([[ 0.5423,  0.1103, -2.2590,  0.6067, -0.1383],
        [ 0.8310, -0.2477, -0.8029,  0.2366,  0.2857]]) 
 tensor([[-0.4791,  1.3790,  2.5286,  0.5423,  0.1103, -2.2590,  0.6067, -0.1383],
        [ 0.4107, -0.9880, -0.9081,  0.8310, -0.2477, -0.8029,  0.2366,  0.2857]])


## Reshaping Tensors
Use the .view() method to reshape a tensor. This method receives heavy use, *because many neural network components expect their inputs to have a certain shape.* Often you will need to reshape before passing your data to the component.

In [4]:
x = torch.randn(2,3,4)
print(x)
print(x.view(2,12))# Reshape this tensor to 2 rows, 12 columns
#If one of the argument of the dimensions is -1, its size can be automatically inferred
print(x.view(2,-1))
print(x.view(4,-1))

tensor([[[-1.4344, -0.5008,  0.1716, -0.1600],
         [-0.5047, -1.4746, -0.3416, -0.3003],
         [ 1.2466,  0.5057,  0.9505,  1.2966]],

        [[ 0.8738, -0.5603,  1.2858,  0.8168],
         [-1.4648, -1.2629,  1.1220,  1.5663],
         [ 2.5581, -0.2334, -0.0135,  1.8606]]])
tensor([[-1.4344, -0.5008,  0.1716, -0.1600, -0.5047, -1.4746, -0.3416, -0.3003,
          1.2466,  0.5057,  0.9505,  1.2966],
        [ 0.8738, -0.5603,  1.2858,  0.8168, -1.4648, -1.2629,  1.1220,  1.5663,
          2.5581, -0.2334, -0.0135,  1.8606]])
tensor([[-1.4344, -0.5008,  0.1716, -0.1600, -0.5047, -1.4746, -0.3416, -0.3003,
          1.2466,  0.5057,  0.9505,  1.2966],
        [ 0.8738, -0.5603,  1.2858,  0.8168, -1.4648, -1.2629,  1.1220,  1.5663,
          2.5581, -0.2334, -0.0135,  1.8606]])
tensor([[-1.4344, -0.5008,  0.1716, -0.1600, -0.5047, -1.4746],
        [-0.3416, -0.3003,  1.2466,  0.5057,  0.9505,  1.2966],
        [ 0.8738, -0.5603,  1.2858,  0.8168, -1.4648, -1.2629],
        [ 1.

In [5]:
x = torch.tensor([1.,2.,3.],requires_grad=True)
y = torch.tensor([4.,5.,6.],requires_grad=True)
z = x+y
print(z)
print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


Tensors know what created them. z knows that it wasn't read in from a file, and it wasn't the result of a multiplication or exponential or what so ever. 

In [6]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [10]:
x.grad.data.zero_()
s.backward()
print(x.grad)


tensor([1., 1., 1.])


In [14]:
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad, y.requires_grad)
z = x + y
print(z.grad_fn)

False False
None


In [17]:
x = x.requires_grad_()
y = y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

True


In [20]:
new_z = z.detach()
print(new_z.grad_fn)

None


In [22]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False
